# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 12:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_historicalmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmessage',
            name='course',
        ),
        migrations.RemoveField(
            model_name='historicalmessage',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalmessage',
            name='user',
        ),
        migrations.DeleteModel(
            name='HistoricalMessage',
        ),
    ]
