# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
