# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 12:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_historicalcourse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalcourse',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='HistoricalCourse',
        ),
    ]
