# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20171115_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='age',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='account',
            name='f_name',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='account',
            name='l_name',
            field=models.CharField(max_length=90),
        ),
    ]
