# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20171127_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='age',
            field=models.CharField(max_length=64),
        ),
    ]
