# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 14:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20171127_1652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='salt',
            new_name='salt1',
        ),
        migrations.AddField(
            model_name='account',
            name='salt2',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='age',
            field=models.CharField(max_length=64),
        ),
    ]
