# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20171127_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountAudit',
            fields=[
                ('email', models.EmailField(max_length=254)),
                ('pwd_hash', models.CharField(max_length=255)),
                ('salt1', models.CharField(max_length=255)),
                ('salt2', models.CharField(max_length=255)),
                ('f_name', models.CharField(max_length=90)),
                ('l_name', models.CharField(max_length=90)),
                ('age', models.CharField(max_length=64)),
                ('_audit_id', models.AutoField(primary_key=True, serialize=False)),
                ('_audit_timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('_audit_change_type', models.CharField(max_length=1)),
                ('id', models.IntegerField(db_index=True, editable=False)),
            ],
            options={
                'db_table': 'account_account_audit',
                'ordering': ['-_audit_timestamp'],
                'verbose_name_plural': 'account audit trail',
            },
        ),
        migrations.RenameField(
            model_name='account',
            old_name='salt',
            new_name='salt1',
        ),
        migrations.AddField(
            model_name='account',
            name='salt2',
            field=models.CharField(default=222, max_length=255),
            preserve_default=False,
        ),
    ]
