# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 02:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        
        ('account', '0005_auto_20171127_2328'),
    ]

    operations = [
    ]


    